#FROM microsoft/windowsservercore
FROM microsoft/iis
COPY *.* c:/
RUN sc create LMDBService start=auto binpath="C:\LMDBService.exe"
RUN sc sdset SCMANAGER D:(A;;CCLCRPRC;;;AU)(A;;CCLCRPWPRC;;;SY)(A;;KA;;;BA)S:(AU;FA;KA;;;WD)(AU;OIIOFA;GA;;;WD)
#RUN net start LMDBService

EXPOSE 80	
EXPOSE 7001	
RUN md c:\temp
