version: LDB-{branch}-{build}

test: off

install:
  - ps: $env:DOTNET_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER

build_script:
  - cmd: build.cmd
  
artifacts:
  - path: artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/lightning-net
    api_key:
      secure: up5/TlcwTcVz+7wVHGnQ1q9iJOdkk4UNehGWaxQ8TqQ21iNqJr8j8m36bTBXMAaO
    skip_symbols: true
    artifact: /.*\.nupkg/